---
#seed: 2
testCase:
- # constant speed
  N: 4
  dt: 0.01
  T: 1.0
  x0: [0, 0, 1, 0]
  Qd: [1, 1, 1, 1]
  Qm: .01
  obs:
    - Rd: [1, 1]
      Rm: .01
  u: [0, 0, 0, -0.1]
- # RTBP
  N: 4
  dt: 0.03
  T: 6.2296051135204102
  x0: [1.033366313746765, 0, 0, -.05849376854515592]
  Qd: [1, 1, 1, 1]
  Qm: .005
  obs:
    - Rd: [1, 1]
      Rm: .001
    - Rd: [1, 1]
      Rm: .0001
      every_X: 10
  u: [0, 0, 0, 0]
- # Vehicle
  GT_to_file: vehicle_data/GT.csv
  U_to_file: vehicle_data/U.csv
  N: 6
  dt: 0.1
  integration_steps: 20
  T: 100
  x0: [0, 0, 0, 1, 0, 0]
  Qd: [0, 0, 0, 1, 1, .5]
  Qm: 1.3
  obs:
    - Rd: [1, 1, .5]
      Rm: .1
      to_file: vehicle_data/IMU.csv
    -
      Rd: [1, 1, .5]
      Rm: .005
      every_X: 100
      to_file: vehicle_data/VISUAL.csv
  u: [0, 0, 0]
  max_steering_angle: 0.174533
- # Vehicle cloning
#  GT_from_file: vehicle_data/GT.csv
#  U_from_file: vehicle_data/IMU.csv
  N: 6
  dt: 0.1
  T: 100
  integration_steps: 20
  x0: [ 0, 0, 0, 1, 0, 0 ]
  Qd: [0, 0, 0, 1, 1, .5]
  Qm: 1.3
  Cd: [1, 1, .5]
  Cm: .1
  obs:
    - Rd: [ 1, 1, .5 ]
      Rm: .05
      every_X: 100
#      from_file: vehicle_data/VISUAL.csv
  u: [ 1, 0, 0 ]
  max_steering_angle: 0.174533
