---
#seed: 2
testCase:
- #1 constant speed
  N: 4
  dt: 0.01
  integration_dt: 0.0001
  T: 1.0
  x0: [0, 0, 1, 0]
  Qd: [1, 1, 1, 1]
  Qm: .01
  obs:
    - Rd: [1, 1]
      Rm: .01
  u: [0, 0, 0, -0.1]
- #2 RTBP
  N: 4
  dt: 0.03
  integration_dt: 0.0003
  T: 6.2296051135204102
  x0: [1.033366313746765, 0, 0, -.05849376854515592]
  Qd: [1, 1, 1, 1]
  Qm: .005
  obs:
    - Rd: [1, 1]
      Rm: .001
    - Rd: [1, 1]
      Rm: .001
      every_X: 10
  u: [0, 0, 0, 0]
- #3 Vehicle
  GT_to_file: vehicle_data/GT.csv
  U_to_file: vehicle_data/U.csv
  N: 6
  dt: 0.1
  integration_dt: 0.005
  T: 100
  x0: [0, 0, 0, 1, 0, 0]
  Qd: [0, 0, 0, 1, 1, .5]
  Qm: 1.3
  obs:
    - Rd: [1, 1, .5]
      Rm: .01
      to_file: vehicle_data/IMU.csv
    -
      Rd: [1, 1, .5]
      Rm: .05
      every_X: 10
      to_file: vehicle_data/VISUAL.csv
  u: [0, 0, 0]
  max_steering_angle: 0.174533
- #4 Vehicle cloning
  N: 6
  dt: 0.1
  T: 100
  integration_dt: 0.005
  x0: [ 0, 0, 0, 1, 0, 0 ]
  Qd: [0, 0, 0, 1, 1, .5]
  Qm: 1.3
  Cd: [1, 1, .5]
  Cm: .1
  obs:
    - Rd: [ 1, 1, .5 ]
      Rm: .05
      every_X: 100
  u: [0, 0, 0]
  max_steering_angle: 0.174533
- #5 Vehicle3 smoothing
  GT_from_file: exoter_logs/log-1/gt.csv
  Time_from_file: exoter_logs/log-1/gt_time.csv
  OTime_from_file: exoter_logs\log-1\dvo_time.csv
  Kalman_to_file: exoter_logs/log-1/gt_vo.csv
  N: 12
  dt: 0.1
  T: 2000000
  integration_dt: 0.01
  x0: [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
  Qd: [0, 0, 0, 0, 0, 0, 1, 1, 1, .1, .1, .1]
  Qm: 0.1
  obs:
    - Rd: [ 1, 1, 1, .1, .1, .1]
      Rm: .05
      from_file: exoter_logs/log-1/gt.csv
  u: [ 0 ]
- #6 Vehicle3 cloning
    GT_from_file: exoter_logs/log_1_filtered.csv
    N: 12
    dt: 0.01
    T: 200
    integration_dt: 0.01
    x0: [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ]
    Qd: [0, 0, 0, 0, 0, 0, 1, 1, 1, .1, .1, .1]
    Qm: 0.01
    Cd: [ 1, 1, 1, 1, 1, 1]
    Cm: .001
    obs:
      - Rd: [ 1, 1, 1, .1, .1, .1]
        every_X: 100
        Rm: .05
    u: [ 0 ]
